apiVersion: stack.kubephos.io/v1alpha1
kind: ManagedStack
metadata:
  version: 0.1.0
spec:
  build:
    go: 1.25.5
    baseImage: alpine:3.23
  platform:
    postgres:
      version: 18.6-alpine3.23
      image: postgres:18.6-alpine3.23
    liquibase:
      version: 4.32.0
      image: liquibase/liquibase:4.32.0
    seaweedfs:
      version: "4.29"
      image: chrislusf/seaweedfs:4.29
